# Generated by Django 4.1.13 on 2024-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_host_host_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlock',
            name='username',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hosteventlog',
            name='username',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
