# Generated by Django 4.1.3 on 2022-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_host_nagios_alter_host_qualys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='nagios',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='qualys',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='syslog_relp_10515',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='syslog_standard_10514',
            field=models.BooleanField(),
        ),
    ]
