# Generated by Django 4.1.3 on 2022-12-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_squashed_0004_alter_host_nagios_alter_host_qualys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.event'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.host'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.staff'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
