# Generated by Django 4.1.13 on 2024-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_logentry_event_logentry_host_logentry_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
