# Generated by Django 4.1.13 on 2024-08-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_host_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='ip_address',
            new_name='ip_addresses',
        ),
    ]
