# Generated by Django 4.1.13 on 2024-08-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_ip_address_host_ip_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags_Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_url', models.URLField(max_length=512)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': '"serviceindex"."tags_loc"',
            },
        ),
    ]
