# Generated by Django 4.1.13 on 2024-08-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_tags_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_loc',
            name='service',
        ),
    ]
