# Generated by Django 5.0.14 on 2025-10-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'db_table': '"serviceindex"."availability"',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': '"serviceindex"."event"',
            },
        ),
        migrations.CreateModel(
            name='Misc_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('urls', models.URLField(max_length=512)),
            ],
            options={
                'db_table': '"serviceindex"."misc_urls"',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('hostname', models.CharField(blank=True, max_length=256)),
                ('failover_process', models.CharField(blank=True, max_length=1024)),
                ('failover_last_tested', models.DateField(blank=True, null=True)),
                ('service_last_verified', models.DateField(blank=True, null=True)),
                ('dependencies', models.CharField(blank=True, max_length=1024)),
                ('lb', models.BooleanField()),
                ('ha', models.BooleanField()),
                ('otp', models.BooleanField()),
                ('nagios', models.BooleanField()),
                ('service_tags', models.CharField(blank=True, max_length=256, null=True)),
                ('deprecated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"serviceindex"."service"',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=256)),
            ],
            options={
                'db_table': '"serviceindex"."site"',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"serviceindex"."staff"',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=256)),
            ],
            options={
                'db_table': '"serviceindex"."support"',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=256)),
                ('ip_addresses', models.CharField(blank=True, max_length=256)),
                ('qualys', models.BooleanField()),
                ('nagios', models.BooleanField()),
                ('syslog_standard_10514', models.BooleanField()),
                ('syslog_relp_10515', models.BooleanField()),
                ('label', models.CharField(max_length=128)),
                ('note', models.CharField(blank=True, max_length=2048)),
                ('host_tags', models.CharField(blank=True, max_length=256, null=True)),
                ('host_last_verified', models.DateField(blank=True, null=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.availability')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site')),
                ('poc_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poc_backup_instance_set', to='web.staff')),
                ('poc_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poc_primary_instance_set', to='web.staff')),
                ('sys_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sys_admin_instance_set', to='web.staff')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.support')),
            ],
            options={
                'db_table': '"serviceindex"."host"',
            },
        ),
        migrations.CreateModel(
            name='HostEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=25)),
                ('note', models.CharField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('unchecked', 'unchecked'), ('in_progress', 'in progress'), ('compliant', 'compliant'), ('na', 'N/A')], max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.host')),
            ],
            options={
                'db_table': '"serviceindex"."hosteventlog"',
            },
        ),
        migrations.CreateModel(
            name='HostEventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unchecked', 'unchecked'), ('in_progress', 'in progress'), ('compliant', 'compliant'), ('na', 'N/A')], max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.host')),
            ],
            options={
                'db_table': '"serviceindex"."hosteventstatus"',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service')),
            ],
            options={
                'db_table': '"serviceindex"."link"',
            },
        ),
        migrations.CreateModel(
            name='EditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=25)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service')),
            ],
            options={
                'db_table': '"serviceindex"."editlock"',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=25)),
                ('msg', models.CharField(max_length=1024)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.event')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.host')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.service')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.staff')),
            ],
            options={
                'db_table': '"serviceindex"."logentry"',
            },
        ),
    ]
